# 1. Carregar e limpar dados

## 1.1 Importações de bibliotecas e base de dados

In [255]:
import pandas as pd
import numpy as np

In [256]:
# Importando base de dados do campeonato brasileiro
df = pd.read_csv("data/campeonato-brasileiro-full.csv")

df.sample(5)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
3312,3315,23,19/09/2010,18:30,Avai,Gremio,NaN,NaN,NaN,NaN,Gremio,Ressacada,0,3,SC,RS,NaN
2791,2792,9,05/07/2009,16:00,Atletico-MG,Botafogo-RJ,NaN,NaN,NaN,NaN,-,Mineirão,1,1,MG,RJ,NaN
7239,7243,36,14/02/2021,20:29,Gremio,Sao Paulo,4-2-3-1,4-4-2,Renato Gaúcho,M. Vizolli,Sao Paulo,Arena do Grêmio,1,2,RS,SP,NaN
4598,4599,38,08/12/2013,18:00,Atletico-MG,Vitoria,NaN,NaN,NaN,NaN,-,Independência,2,2,MG,BA,NaN
8310,8311,29,25/10/2023,21:30,Gremio,Flamengo,3-4-2-1,4-2-3-1,Renato Gaúcho,A. Bacchi,Gremio,Arena do Grêmio,3,2,RS,RJ,NaN

## 1.2 Análise exploratória dos dados

In [257]:
# Verificando colunas do DataFrame
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado',
       'arrecadacao'],
      dtype='str')

In [258]:
# Mantendo apenas as colunas que serão utilizadas
df = df[['rodata','data','mandante','visitante', 'mandante_Placar', 'visitante_Placar']]

In [259]:
# Contagem de linhas e colunas do DataFrame
df.shape

(9165, 6)

In [260]:
# Verificando tipos das colunas e valores nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rodata            9165 non-null   int64
 1   data              9165 non-null   str
 2   mandante          9165 non-null   str
 3   visitante         9165 non-null   str
 4   mandante_Placar   9165 non-null   int64
 5   visitante_Placar  9165 non-null   int64
dtypes: int64(3), str(3)
memory usage: 429.7 KB

# 1.3 Limpeza e formatação

In [261]:
# Corrigindo coluna data para o tipo datetime
df['data'] = pd.to_datetime(df['data'], format='%d/%m/%Y')

In [262]:
# Renomeando colunas para facilitar a manipulação dos dados
df = df.rename(columns={'rodata':'rodada', 'data':'data', 'mandante':'mandante', 'visitante':'visitante', 'vencedor':'vencedor', 'mandante_Placar':'placar_mandante', 'visitante_Placar':'placar_visitante'})

In [263]:
# Filtrando apenas os jogos a partir de 2006, ano em que o campeonato brasileiro passou a ser disputado no formato atual
df = df[df['data'] >= '2006-01-01']

In [264]:
# Nova quantidade de linhas do DataFrame após o filtro
df.shape

(7599, 6)

In [265]:
df.head()

,rodada,data,mandante,visitante,placar_mandante,placar_visitante
1566,1,2006-04-15,Juventude,Parana,1,0
1567,1,2006-04-15,Vasco,Internacional,1,1
1568,1,2006-04-16,Sao Paulo,Flamengo,1,0
1569,1,2006-04-16,Gremio,Corinthians,2,0
1570,1,2006-04-16,Botafogo-RJ,Fortaleza,1,0

In [266]:
# Arrumando o índice do DataFrame após o filtro
df = df.reset_index(drop=True).sort_values(by=['data', 'rodada'], ascending=[True, True])

In [267]:
# Verificando o período de tempo dos dados
print(df['data'].min())
print(df['data'].max())

2006-04-15 00:00:00
2025-12-07 00:00:00

## 1.4 Criação de novas colunas

In [268]:
# Criando a coluna 'ano'
df['ano'] = df['data'].dt.year

In [269]:
# Contando quantos jogos tiveram no ano. Metade dos jogos de 2020 foram realizados em 2021
df.groupby('ano')['rodada'].count()

ano
2006    380
2007    380
2008    380
2009    380
2010    380
2011    380
2012    380
2013    380
2014    380
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2024    380
2025    380
Name: rodada, dtype: int64

In [270]:
# Entendendo quando começou o Brasileirão 2021 de fato
df[(df['ano'] == 2021) & (df['rodada'] == 1)]

,rodada,data,mandante,visitante,placar_mandante,placar_visitante,ano
5635,1,2021-01-26,Palmeiras,Vasco,1,1,2021
5699,1,2021-05-29,Cuiaba,Juventude,2,2,2021
5700,1,2021-05-29,Bahia,Santos,3,0,2021
5701,1,2021-05-29,Sao Paulo,Fluminense,0,0,2021
5702,1,2021-05-30,Atletico-MG,Fortaleza,1,2,2021
5703,1,2021-05-30,Ceara,Gremio,3,2,2021
5704,1,2021-05-30,Flamengo,Palmeiras,1,0,2021
5705,1,2021-05-30,Chapecoense,Bragantino,0,3,2021
5706,1,2021-05-30,Corinthians,Atletico-GO,0,1,2021
5707,1,2021-05-30,Athletico-PR,America-MG,1,0,2021
5708,1,2021-05-30,Internacional,Sport,2,2,2021

In [271]:
# Alterando para que a coluna de ano mostre em qual temporada o ocorreu o jogo
df['ano'] = np.where(
    (df['ano'] == 2021) & (df['data'] < '2021-04-01'),
    2020,
    df['ano']
)

In [272]:
# Condições pontuação do time mandante
condicoes_pontuacao_mandante = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_visitante'] > df['placar_mandante']
]

# Quantidade de pontos baseado na condição
pontuacao = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_mandante'] = np.select(condicoes_pontuacao_mandante, pontuacao)

In [273]:
# Condições pontuação do time visitante
condicoes_pontuacao_visitante = [
    df['placar_visitante'] > df['placar_mandante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] > df['placar_visitante']
]

# Quantidade de pontos baseado na condição
pontuacao = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_visitante'] = np.select(condicoes_pontuacao_visitante, pontuacao)

In [274]:
condicoes_resultado = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] < df['placar_visitante']
]

resultados = ['M', 'E', 'V']

df['resultado'] = np.select(condicoes_resultado, resultados, default='Indefinido')

In [275]:
condicoes_resultado = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] < df['placar_visitante']
]

resultados = [1, 0.5, 0]

df['resultado_elo_mandante'] = np.select(condicoes_resultado, resultados)
df['resultado_elo_visitante'] = (1-(np.select(condicoes_resultado, resultados)))

In [276]:
df.sample(5)

,rodada,data,mandante,visitante,placar_mandante,placar_visitante,ano,pontos_mandante,pontos_visitante,resultado,resultado_elo_mandante,resultado_elo_visitante
2070,18,2011-08-20,Corinthians,Figueirense,0,2,2011,0,3,V,0.0,1.0
1933,4,2011-06-11,Vasco,Figueirense,1,1,2011,1,1,E,0.5,0.5
5117,18,2019-09-08,CSA,Chapecoense,2,0,2019,3,0,M,1.0,0.0
4248,7,2017-06-15,Fluminense,Gremio,0,2,2017,0,3,V,0.0,1.0
5846,16,2021-08-14,Atletico-MG,Palmeiras,2,0,2021,3,0,M,1.0,0.0

# 2. Classificação de uma temporada específica (teste de sanidade)

## 2.1 Criando dataframes do time mandante

In [277]:
# Criando dataframe apenas com os jogos dos times mandante
df_mandante = df[['rodada', 'data', 'ano', 'mandante', 'placar_mandante', 'placar_visitante', 'pontos_mandante', 'visitante']]

# Renomeando as colunas
df_mandante = df_mandante.rename(columns={'rodada':'rodada', 'data':'data', 'ano':'ano', 'mandante':'time', 'placar_mandante':'gols_pro', 'placar_visitante':'gols_contra', 'pontos_mandante':'pontos', 'visitante':'adversario'})

In [278]:
condicoes_resultado_mandante = [
    df_mandante['gols_pro'] > df_mandante['gols_contra'],
    df_mandante['gols_pro'] == df_mandante['gols_contra'],
    df_mandante['gols_pro'] < df_mandante['gols_contra']
]

resultado_mandante = ['M', 'E', 'V']

In [279]:
df_mandante['mando'] = 1

df_mandante['resultado'] = np.select(condicoes_resultado_mandante, resultado_mandante, default='Indefinido')

df_mandante.head()

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
0,1,2006-04-15,2006,Juventude,1,0,3,Parana,1,M
1,1,2006-04-15,2006,Vasco,1,1,1,Internacional,1,E
2,1,2006-04-16,2006,Sao Paulo,1,0,3,Flamengo,1,M
3,1,2006-04-16,2006,Gremio,2,0,3,Corinthians,1,M
4,1,2006-04-16,2006,Botafogo-RJ,1,0,3,Fortaleza,1,M

## 2.2 Criando dataframe com jogos do time visitante

In [280]:
# Criando dataframe apenas com os jogos dos times visitantes
df_visitante = df[['rodada', 'data', 'ano', 'visitante', 'placar_visitante', 'placar_mandante', 'pontos_visitante', 'mandante']]

# Renomeando as colunas
df_visitante = df_visitante.rename(columns={'rodada':'rodada', 'data':'data', 'ano':'ano', 'visitante':'time', 'placar_visitante':'gols_pro', 'placar_mandante':'gols_contra', 'pontos_visitante':'pontos', 'mandante':'adversario'})

In [281]:
condicoes_resultado_visitante = [
    df_visitante['gols_pro'] > df_visitante['gols_contra'],
    df_visitante['gols_pro'] == df_visitante['gols_contra'],
    df_visitante['gols_pro'] < df_visitante['gols_contra']
]

resultado_visitante = ['V', 'E', 'M']

In [282]:
df_visitante['mando'] = 0

df_visitante['resultado'] = np.select(condicoes_resultado_visitante, resultado_visitante, default='Indefinido')

df_visitante.head()

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
0,1,2006-04-15,2006,Parana,0,1,0,Juventude,0,M
1,1,2006-04-15,2006,Internacional,1,1,1,Vasco,0,E
2,1,2006-04-16,2006,Flamengo,0,1,0,Sao Paulo,0,M
3,1,2006-04-16,2006,Corinthians,0,2,0,Gremio,0,M
4,1,2006-04-16,2006,Fortaleza,0,1,0,Botafogo-RJ,0,M

## 2.3 Juntando dataframes de mandante e visitante em um

In [283]:
# Juntando os dois dataframes em um único
df_tabela_total = pd.concat([df_mandante, df_visitante])
df_tabela_total.sample(5)

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
4863,31,2018-10-27,2018,America-MG,0,1,0,Chapecoense,0,M
6745,29,2023-10-25,2023,Corinthians,1,0,3,Cuiaba,0,V
5812,12,2021-07-18,2021,Santos,2,2,1,Bragantino,0,E
7258,4,2025-04-17,2025,Bahia,0,3,0,Cruzeiro,0,M
6959,13,2024-06-30,2024,Bahia,1,3,0,Sao Paulo,0,M

## 2.4 Criando tabela de uma temporada específica a partir dos dados

In [284]:
# Filtrando os dados para o ano de 2024
df_2024 = df_tabela_total[df_tabela_total['ano'] == 2024]

# Agrupando por time e somando APENAS gols_pro, gols_contra e pontos e ordenando por pontos
df_ranking = df_2024.groupby('time')[['gols_pro', 'gols_contra', 'pontos']].sum().sort_values(by='pontos', ascending=False)

df_ranking

               gols_pro  gols_contra  pontos
time
Botafogo-RJ          59           29      79
Palmeiras            60           33      73
Flamengo             61           42      70
Fortaleza            53           39      68
Internacional        53           36      65
Sao Paulo            53           43      59
Corinthians          54           45      56
Bahia                49           49      53
Cruzeiro             43           41      52
Vasco                43           56      50
Atletico-MG          47           54      47
Vitoria              45           52      47
Fluminense           33           39      46
Juventude            48           59      45
Gremio               44           50      45
Bragantino           44           48      44
Athletico-PR         40           46      42
Criciuma             42           61      38
Atletico-GO          29           58      30
Cuiaba               29           49      30

In [285]:
# Checa se a coluna 'data' está ordenada
df['data'].is_monotonic_increasing

True

# 3. Cálculo de elo dos times

## 3.1 Resultado esperado de cada jogo sendo mandante (M: Mandante venceu, E: Empate, V: Visitante venceu)

In [286]:
df.value_counts('resultado', normalize=True) *100

resultado
M    49.085406
E    26.792999
V    24.121595
Name: proportion, dtype: float64

## 3.2 Funções para calcular Elo de cada time

In [287]:
def prob_esperada_m(mandante, visitante, h):
    return 1/(1 + 10**((visitante - (mandante + h))/400))

In [288]:
def prob_esperada_v(visitante, mandante, h):
    return 1/(1 + 10**(((mandante + h) - visitante )/400))

In [289]:
def atualizar_elo_m(mandante, resultado, probabilidade_m):
    return mandante + 20 * (resultado-probabilidade_m)

In [290]:
def atualizar_elo_v(visitante, resultado, probabilidade_v):
    return visitante + 20 * (resultado - probabilidade_v)

## 3.3 Loop de cálculo do elo em cada jogo

In [291]:
h = 100

In [ ]:
# Criando dicionário que guarda o elo de cada time
elo = {}

# Listas que salvam o elo do time antes de uma partida, para ser atualizado
elo_mandante_antes = []
elo_visitante_antes = []

# Loop de atualização do elo de cada time
for jogo in df.itertuples():

    # Busca o elo do time selecionado, caso o time ainda não esteja salvo, atribui elo 1500
    elo_m = elo.get(jogo.mandante, 1500)
    elo_v = elo.get(jogo.visitante, 1500)

    # Salva o elo do time antes da partida
    elo_mandante_antes.append(elo_m)
    elo_visitante_antes.append(elo_v)

    # Usa a função que calcula a probabilidade do time vencer a partida baseada no elo, considerando a vantagem do mandante (h)
    prob_m = prob_esperada_m(elo_m, elo_v, h)
    prob_v = prob_esperada_v(elo_v, elo_m, h)
    
    # Usa a função que atualiza o elo da equipe baseado no resultado real da partida
    novo_elo_m = atualizar_elo_m(elo_m, jogo.resultado_elo_mandante, prob_m)
    novo_elo_v = atualizar_elo_v(elo_v, jogo.resultado_elo_visitante, prob_v)

    # Atualiza o dicionário com o novo elo do time
    elo[jogo.mandante] = novo_elo_m
    elo[jogo.visitante] = novo_elo_v

In [ ]:
# Cria coluna com o elo de cada time em cada partida jogada, desde quando todos tinham 1500 de elo até o último
df['elo_mandante_antes'] = elo_mandante_antes
df['elo_visitante_antes'] = elo_visitante_antes

In [ ]:
# Teste para saber se os elos estão batendo
print(sum(elo.values()))
print(1500*len(elo))

66000.0
66000

In [ ]:
# Resultado final do elo de cada time633
dict(sorted(elo.items(), key=lambda item: item[1], reverse=True))

{'Flamengo': 1719.284775190617,
 'Palmeiras': 1706.4190444777112,
 'Botafogo-RJ': 1669.8052133725002,
 'Cruzeiro': 1635.5985298300786,
 'Fluminense': 1632.9635533306882,
 'Mirassol': 1618.429543180488,
 'Fortaleza': 1575.3491698046296,
 'Bahia': 1575.3030721898683,
 'Sao Paulo': 1567.84865744514,
 'Corinthians': 1566.0052850927375,
 'Internacional': 1559.8538460060624,
 'Gremio': 1559.2542825050452,
 'Atletico-MG': 1554.4994874573251,
 'Santos': 1549.877584238483,
 'Vitoria': 1541.9318590937935,
 'Portuguesa': 1526.1452327250781,
 'Bragantino': 1525.125817611716,
 'Vasco': 1522.6047341534472,
 'Athletico-PR': 1510.1055564340581,
 'Barueri': 1503.2111586827223,
 'Ceara': 1496.1009824032965,
 'Goias': 1483.1508178896777,
 'Ponte Preta': 1474.407664768016,
 'Santo Andre': 1471.7008845151563,
 'Juventude': 1468.0376461712294,
 'Figueirense': 1462.0770461148045,
 'Cuiaba': 1461.6888623923417,
 'Criciuma': 1452.2343474127024,
 'Atletico-GO': 1449.7085194734861,
 'Ipatinga': 1448.0208647247046,
 'Guarani': 1446.2812559514934,
 'America-MG': 1444.0739208657099,
 'Joinville': 1442.6379711490931,
 'CSA': 1437.7907631489736,
 'Coritiba': 1432.7597465693232,
 'Gremio Prudente': 1426.525737937153,
 'Sao Caetano': 1420.7745953806373,
 'Avai': 1411.9335528562406,
 'Parana': 1393.57971615178,
 'Santa Cruz': 1386.5768341090593,
 'Sport': 1381.5528372094216,
 'Nautico': 1377.356349960579,
 'Chapecoense': 1365.1059055500975,
 'America-RN': 1346.3067744728326}