# 1. Carregar e limpar dados

## 1.1 Importações de bibliotecas e base de dados

In [83]:
import pandas as pd
import numpy as np

In [84]:
# Importando base de dados do campeonato brasileiro
df = pd.read_csv("data/campeonato-brasileiro-full.csv")

df.sample(5)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
9094,9098,32,05/11/2025,19:01,Bragantino,Corinthians,4-2-3-1,3-4-1-2,V. Mancini,D. Junior,Bragantino,"Estádio Municipal Cicero De Souza Marques, Bra...",2,1,SP,SP,395515.0
3237,3239,16,25/08/2010,19:30,Avai,Internacional,NaN,NaN,NaN,NaN,Internacional,Ressacada,0,1,SC,RS,NaN
3036,3037,34,04/11/2009,21:50,Gremio,Sao Paulo,NaN,NaN,NaN,NaN,-,Olímpico,1,1,RS,SP,NaN
4706,4718,11,19/07/2014,18:30,Figueirense,Gremio,NaN,NaN,A. Ferreira,E. Alves Moreira,Gremio,Orlando Scarpelli,0,1,SC,RS,NaN
5496,5497,14,09/07/2016,16:31,Chapecoense,Corinthians,4-3-2-1,4-2-3-1,L. Saroli Caio Júnior,C. Borges dos Santos,Corinthians,Arena Condá,0,2,SC,SP,NaN

## 1.2 Análise exploratória dos dados

In [85]:
# Verificando colunas do DataFrame
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado',
       'arrecadacao'],
      dtype='str')

In [86]:
# Mantendo apenas as colunas que serão utilizadas
df = df[['rodata','data','mandante','visitante', 'mandante_Placar', 'visitante_Placar']]

In [87]:
# Contagem de linhas e colunas do DataFrame
df.shape

(9165, 6)

In [88]:
# Verificando tipos das colunas e valores nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rodata            9165 non-null   int64
 1   data              9165 non-null   str
 2   mandante          9165 non-null   str
 3   visitante         9165 non-null   str
 4   mandante_Placar   9165 non-null   int64
 5   visitante_Placar  9165 non-null   int64
dtypes: int64(3), str(3)
memory usage: 429.7 KB

# 1.3 Limpeza e formatação

In [89]:
# Corrigindo coluna data para o tipo datetime
df['data'] = pd.to_datetime(df['data'], format='%d/%m/%Y')

In [90]:
# Renomeando colunas para facilitar a manipulação dos dados
df = df.rename(columns={'rodata':'rodada', 'data':'data', 'mandante':'mandante', 'visitante':'visitante', 'vencedor':'vencedor', 'mandante_Placar':'placar_mandante', 'visitante_Placar':'placar_visitante'})

In [91]:
# Filtrando apenas os jogos a partir de 2006, ano em que o campeonato brasileiro passou a ser disputado no formato atual
df = df[df['data'] >= '2006-01-01']

In [92]:
# Nova quantidade de linhas do DataFrame após o filtro
df.shape

(7599, 6)

In [93]:
df.head()

,rodada,data,mandante,visitante,placar_mandante,placar_visitante
1566,1,2006-04-15,Juventude,Parana,1,0
1567,1,2006-04-15,Vasco,Internacional,1,1
1568,1,2006-04-16,Sao Paulo,Flamengo,1,0
1569,1,2006-04-16,Gremio,Corinthians,2,0
1570,1,2006-04-16,Botafogo-RJ,Fortaleza,1,0

In [94]:
# Arrumando o índice do DataFrame após o filtro
df = df.reset_index(drop=True).sort_values(by=['data', 'rodada'], ascending=[True, True])

In [95]:
# Verificando o período de tempo dos dados
print(df['data'].min())
print(df['data'].max())

2006-04-15 00:00:00
2025-12-07 00:00:00

## 1.4 Criação de novas colunas

In [96]:
# Criando a coluna 'ano'
df['ano'] = df['data'].dt.year

In [97]:
# Contando quantos jogos tiveram no ano. Metade dos jogos de 2020 foram realizados em 2021
df.groupby('ano')['rodada'].count()

ano
2006    380
2007    380
2008    380
2009    380
2010    380
2011    380
2012    380
2013    380
2014    380
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2024    380
2025    380
Name: rodada, dtype: int64

In [98]:
# Entendendo quando começou o Brasileirão 2021 de fato
df[(df['ano'] == 2021) & (df['rodada'] == 1)]

,rodada,data,mandante,visitante,placar_mandante,placar_visitante,ano
5635,1,2021-01-26,Palmeiras,Vasco,1,1,2021
5699,1,2021-05-29,Cuiaba,Juventude,2,2,2021
5700,1,2021-05-29,Bahia,Santos,3,0,2021
5701,1,2021-05-29,Sao Paulo,Fluminense,0,0,2021
5702,1,2021-05-30,Atletico-MG,Fortaleza,1,2,2021
5703,1,2021-05-30,Ceara,Gremio,3,2,2021
5704,1,2021-05-30,Flamengo,Palmeiras,1,0,2021
5705,1,2021-05-30,Chapecoense,Bragantino,0,3,2021
5706,1,2021-05-30,Corinthians,Atletico-GO,0,1,2021
5707,1,2021-05-30,Athletico-PR,America-MG,1,0,2021
5708,1,2021-05-30,Internacional,Sport,2,2,2021

In [99]:
# Alterando para que a coluna de ano mostre em qual temporada o ocorreu o jogo
df['ano'] = np.where(
    (df['ano'] == 2021) & (df['data'] < '2021-04-01'),
    2020,
    df['ano']
)

In [100]:
# Condições pontuação do time mandante
condicoes_pontuacao_mandante = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_visitante'] > df['placar_mandante']
]

# Quantidade de pontos baseado na condição
pontuacao = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_mandante'] = np.select(condicoes_pontuacao_mandante, pontuacao)

In [101]:
# Condições pontuação do time visitante
condicoes_pontuacao_visitante = [
    df['placar_visitante'] > df['placar_mandante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] > df['placar_visitante']
]

# Quantidade de pontos baseado na condição
pontuacao = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_visitante'] = np.select(condicoes_pontuacao_visitante, pontuacao)

In [102]:
condicoes_resultado = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] < df['placar_visitante']
]

resultados = ['M', 'E', 'V']

df['resultado'] = np.select(condicoes_resultado, resultados, default='Indefinido')

In [103]:
condicoes_resultado = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] < df['placar_visitante']
]

resultados = [1, 0.5, 0]

df['resultado_elo_mandante'] = np.select(condicoes_resultado, resultados)
df['resultado_elo_visitante'] = (1-(np.select(condicoes_resultado, resultados)))

In [104]:
df.sample(5)

,rodada,data,mandante,visitante,placar_mandante,placar_visitante,ano,pontos_mandante,pontos_visitante,resultado,resultado_elo_mandante,resultado_elo_visitante
7532,32,2025-11-05,Sao Paulo,Flamengo,2,2,2025,1,1,E,0.5,0.5
5200,27,2019-10-19,Corinthians,Cruzeiro,1,2,2019,0,3,V,0.0,1.0
1639,12,2010-08-01,Gremio Prudente,Santos,1,2,2010,0,3,V,0.0,1.0
4025,23,2016-09-07,Coritiba,Gremio,4,0,2016,3,0,M,1.0,0.0
3301,27,2014-10-08,Botafogo-RJ,Palmeiras,0,1,2014,0,3,V,0.0,1.0

# 2. Classificação de uma temporada específica (teste de sanidade)

## 2.1 Criando dataframes do time mandante

In [105]:
# Criando dataframe apenas com os jogos dos times mandante
df_mandante = df[['rodada', 'data', 'ano', 'mandante', 'placar_mandante', 'placar_visitante', 'pontos_mandante', 'visitante']]

# Renomeando as colunas
df_mandante = df_mandante.rename(columns={'rodada':'rodada', 'data':'data', 'ano':'ano', 'mandante':'time', 'placar_mandante':'gols_pro', 'placar_visitante':'gols_contra', 'pontos_mandante':'pontos', 'visitante':'adversario'})

In [106]:
condicoes_resultado_mandante = [
    df_mandante['gols_pro'] > df_mandante['gols_contra'],
    df_mandante['gols_pro'] == df_mandante['gols_contra'],
    df_mandante['gols_pro'] < df_mandante['gols_contra']
]

resultado_mandante = ['M', 'E', 'V']

In [107]:
df_mandante['mando'] = 1

df_mandante['resultado'] = np.select(condicoes_resultado_mandante, resultado_mandante, default='Indefinido')

df_mandante.head()

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
0,1,2006-04-15,2006,Juventude,1,0,3,Parana,1,M
1,1,2006-04-15,2006,Vasco,1,1,1,Internacional,1,E
2,1,2006-04-16,2006,Sao Paulo,1,0,3,Flamengo,1,M
3,1,2006-04-16,2006,Gremio,2,0,3,Corinthians,1,M
4,1,2006-04-16,2006,Botafogo-RJ,1,0,3,Fortaleza,1,M

## 2.2 Criando dataframe com jogos do time visitante

In [108]:
# Criando dataframe apenas com os jogos dos times visitantes
df_visitante = df[['rodada', 'data', 'ano', 'visitante', 'placar_visitante', 'placar_mandante', 'pontos_visitante', 'mandante']]

# Renomeando as colunas
df_visitante = df_visitante.rename(columns={'rodada':'rodada', 'data':'data', 'ano':'ano', 'visitante':'time', 'placar_visitante':'gols_pro', 'placar_mandante':'gols_contra', 'pontos_visitante':'pontos', 'mandante':'adversario'})

In [109]:
condicoes_resultado_visitante = [
    df_visitante['gols_pro'] > df_visitante['gols_contra'],
    df_visitante['gols_pro'] == df_visitante['gols_contra'],
    df_visitante['gols_pro'] < df_visitante['gols_contra']
]

resultado_visitante = ['V', 'E', 'M']

In [110]:
df_visitante['mando'] = 0

df_visitante['resultado'] = np.select(condicoes_resultado_visitante, resultado_visitante, default='Indefinido')

df_visitante.head()

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
0,1,2006-04-15,2006,Parana,0,1,0,Juventude,0,M
1,1,2006-04-15,2006,Internacional,1,1,1,Vasco,0,E
2,1,2006-04-16,2006,Flamengo,0,1,0,Sao Paulo,0,M
3,1,2006-04-16,2006,Corinthians,0,2,0,Gremio,0,M
4,1,2006-04-16,2006,Fortaleza,0,1,0,Botafogo-RJ,0,M

## 2.3 Juntando dataframes de mandante e visitante em um

In [111]:
# Juntando os dois dataframes em um único
df_tabela_total = pd.concat([df_mandante, df_visitante])
df_tabela_total.sample(5)

,rodada,data,ano,time,gols_pro,gols_contra,pontos,adversario,mando,resultado
2689,4,2013-06-05,2013,Internacional,1,1,1,Portuguesa,0,E
467,9,2007-07-04,2007,Vasco,4,0,3,Santos,1,M
6839,1,2024-04-13,2024,Bahia,1,2,0,Internacional,0,M
6605,15,2023-07-16,2023,Palmeiras,0,0,1,Internacional,0,E
3641,23,2015-09-05,2015,Vasco,1,2,0,Atletico-MG,1,V

## 2.4 Criando tabela de uma temporada específica a partir dos dados

In [112]:
# Filtrando os dados para o ano de 2024
df_2024 = df_tabela_total[df_tabela_total['ano'] == 2024]

# Agrupando por time e somando APENAS gols_pro, gols_contra e pontos e ordenando por pontos
df_ranking = df_2024.groupby('time')[['gols_pro', 'gols_contra', 'pontos']].sum().sort_values(by='pontos', ascending=False)

df_ranking

               gols_pro  gols_contra  pontos
time
Botafogo-RJ          59           29      79
Palmeiras            60           33      73
Flamengo             61           42      70
Fortaleza            53           39      68
Internacional        53           36      65
Sao Paulo            53           43      59
Corinthians          54           45      56
Bahia                49           49      53
Cruzeiro             43           41      52
Vasco                43           56      50
Atletico-MG          47           54      47
Vitoria              45           52      47
Fluminense           33           39      46
Juventude            48           59      45
Gremio               44           50      45
Bragantino           44           48      44
Athletico-PR         40           46      42
Criciuma             42           61      38
Atletico-GO          29           58      30
Cuiaba               29           49      30

# 3. Cálculo de elo dos times

## 3.1 Resultado esperado de cada jogo sendo mandante (M: Mandante venceu, E: Empate, V: Visitante venceu)

In [113]:
df.value_counts('resultado', normalize=True) *100

resultado
M    49.085406
E    26.792999
V    24.121595
Name: proportion, dtype: float64

## 3.2 Funções para calcular Elo de cada time

In [114]:
def prob_esperada_m(mandante, visitante, h):
    return 1/(1 + 10**((visitante - (mandante + h))/400))

In [115]:
def prob_esperada_v(mandante, visitante, h):
    return 1/(1 + 10**(((mandante + h) - visitante )/400))

In [116]:
def atualizar_elo_m(mandante, resultado, probabilidade_m):
    return mandante + 20 * (resultado-probabilidade_m)

In [117]:
def atualizar_elo_v(visitante, resultado, probabilidade_v):
    return visitante + 20 * (resultado - probabilidade_v)

## 3.3 Loop de cálculo do elo em cada jogo

In [118]:
h = 100

In [119]:
elo = {}
elo_mandante_antes = []
elo_visitante_antes = []

for jogo in df.itertuples():
    elo_m = elo.get(jogo.mandante, 1500)
    elo_v = elo.get(jogo.visitante, 1500)

    elo_mandante_antes.append(elo_m)
    elo_visitante_antes.append(elo_v)

    prob_m = prob_esperada_m(elo_m, elo_v, h)
    prob_v = prob_esperada_v(elo_v, elo_m, h)
   
    novo_elo_m = atualizar_elo_m(elo_m, jogo.resultado_elo_mandante, prob_m)
    novo_elo_v = atualizar_elo_v(elo_v, jogo.resultado_elo_visitante, prob_v)

    elo[jogo.mandante] = novo_elo_m
    elo[jogo.visitante] = novo_elo_v

In [120]:
df['elo_mandante_antes'] = elo_mandante_antes
df['elo_visitante_antes'] = elo_visitante_antes

In [121]:
df.head(380)

,rodada,data,mandante,visitante,placar_mandante,placar_visitante,ano,pontos_mandante,pontos_visitante,resultado,resultado_elo_mandante,resultado_elo_visitante,elo_mandante_antes,elo_visitante_antes
0,1,2006-04-15,Juventude,Parana,1,0,2006,3,0,M,1.0,0.0,1500.000000,1500.000000
1,1,2006-04-15,Vasco,Internacional,1,1,2006,1,1,E,0.5,0.5,1500.000000,1500.000000
2,1,2006-04-16,Sao Paulo,Flamengo,1,0,2006,3,0,M,1.0,0.0,1500.000000,1500.000000
3,1,2006-04-16,Gremio,Corinthians,2,0,2006,3,0,M,1.0,0.0,1500.000000,1500.000000
4,1,2006-04-16,Botafogo-RJ,Fortaleza,1,0,2006,3,0,M,1.0,0.0,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,38,2006-12-03,Cruzeiro,Botafogo-RJ,3,1,2006,3,0,M,1.0,0.0,1506.576206,1500.791971
376,38,2006-12-03,Ponte Preta,Athletico-PR,1,1,2006,1,1,E,0.5,0.5,1407.913267,1463.960220
377,38,2006-12-03,Corinthians,Juventude,5,3,2006,3,0,M,1.0,0.0,1487.468874,1462.718980
378,38,2006-12-03,Fortaleza,Gremio,1,0,2006,3,0,M,1.0,0.0,1403.362073,1599.477982
379,38,2006-12-03,Santos,Santa Cruz,3,1,2006,3,0,M,1.0,0.0,1575.213414,1340.151923