In [138]:
import pandas as pd

In [139]:
# Importando base de dados do campeonato brasileiro
df = pd.read_csv("data/campeonato-brasileiro-full.csv")

df.sample(5)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
1085,1086,45,12/12/2004,16:00,Sao Caetano,Santos,NaN,NaN,NaN,NaN,Santos,Anacleto Campanella,0,3,SP,SP,NaN
3845,3846,38,04/12/2011,17:00,Athletico-PR,Coritiba,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,1,0,PR,PR,NaN
5072,5073,9,28/06/2015,16:02,Ponte Preta,Athletico-PR,4-2-3-1,4-2-3-1,A. Ferreira,M. Mendes,Ponte Preta,Moisés Lucarelli,2,1,SP,PR,NaN
14,15,2,05/04/2003,16:00,Coritiba,Internacional,NaN,NaN,NaN,NaN,Internacional,Couto Pereira,0,1,PR,RS,NaN
3197,3198,12,31/07/2010,18:30,Fluminense,Athletico-PR,NaN,NaN,NaN,NaN,Fluminense,Maracanã,3,1,RJ,PR,NaN

In [140]:
# Verificando colunas do DataFrame
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado',
       'arrecadacao'],
      dtype='str')

In [141]:
# Mantendo apenas as colunas que serão utilizadas
df = df[['rodata','data','mandante','visitante','vencedor', 'mandante_Placar', 'visitante_Placar']]

In [142]:
# Contagem de linhas e colunas do DataFrame
df.shape

(9165, 7)

In [143]:
# Verificando tipos das colunas e valores nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rodata            9165 non-null   int64
 1   data              9165 non-null   str
 2   mandante          9165 non-null   str
 3   visitante         9165 non-null   str
 4   vencedor          9165 non-null   str
 5   mandante_Placar   9165 non-null   int64
 6   visitante_Placar  9165 non-null   int64
dtypes: int64(3), str(4)
memory usage: 501.3 KB

In [144]:
# Corrigindo coluna data para o tipo datetime
df['data'] = pd.to_datetime(df['data'], format='%d/%m/%Y')

In [145]:
# Renomeando colunas para facilitar a manipulação dos dados
df.rename(columns={'rodata':'rodada', 'data':'data', 'mandante':'mandante', 'visitante':'visitante', 'vencedor':'vencedor', 'mandante_Placar':'placar_mandante', 'visitante_Placar':'placar_visitante'}, inplace=True)

C:\Users\luluj\AppData\Local\Temp\ipykernel_20152\843188354.py:2: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.rename(columns={'rodata':'rodada', 'data':'data', 'mandante':'mandante', 'visitante':'visitante', 'vencedor':'vencedor', 'mandante_Placar':'placar_mandante', 'visitante_Placar':'placar_visitante'}, inplace=True)

In [146]:
# Filtrando apenas os jogos a partir de 2006, ano em que o campeonato brasileiro passou a ser disputado no formato atual
df = df[df['data'] >= '01/01/2006']

In [147]:
# Nova quantidade de linhas do DataFrame após o filtro
df.shape

(7599, 7)

In [148]:
df.head()

,rodada,data,mandante,visitante,vencedor,placar_mandante,placar_visitante
1566,1,2006-04-15,Juventude,Parana,Juventude,1,0
1567,1,2006-04-15,Vasco,Internacional,-,1,1
1568,1,2006-04-16,Sao Paulo,Flamengo,Sao Paulo,1,0
1569,1,2006-04-16,Gremio,Corinthians,Gremio,2,0
1570,1,2006-04-16,Botafogo-RJ,Fortaleza,Botafogo-RJ,1,0

In [149]:
# Arrumando o índice do DataFrame após o filtro
df.reset_index(drop=True, inplace=True)

C:\Users\luluj\AppData\Local\Temp\ipykernel_20152\732740507.py:2: Pandas4Warning: The inplace keyword in DataFrame.reset_index is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.reset_index(drop=True, inplace=True)

In [150]:
# Verificando o período de tempo dos dados
print(df['data'].min())
print(df['data'].max())

2006-04-15 00:00:00
2025-12-07 00:00:00