In [392]:
import pandas as pd
import numpy as np

In [393]:
# Importando base de dados do campeonato brasileiro
df = pd.read_csv("data/campeonato-brasileiro-full.csv")

df.sample(5)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
2154,2167,22,29/08/2007,19:30,Parana,Cruzeiro,NaN,NaN,NaN,NaN,-,Durival de Brito,2,2,PR,MG,NaN
5755,5756,2,20/05/2017,16:01,Santos,Coritiba,4-2-3-1,4-3-3,D. Silvestre Júnior,E. Pacheco,Santos,Estádio Urbano Caldeira,1,0,SP,PR,NaN
9013,9025,24,21/09/2025,20:31,Santos,Sao Paulo,4-2-3-1,3-4-1-2,J. Vojvoda,H. Crespo,Santos,"Estádio Urbano Caldeira, Santos",1,0,SP,SP,707091.17
5389,5390,3,25/05/2016,21:00,America-MG,Vitoria,4-2-3-1,4-2-3-1,G. de Oliveira,V. Carmo Mancini,-,Estádio Raimundo Sampaio,1,1,MG,BA,NaN
3136,3137,6,02/06/2010,19:30,Athletico-PR,Botafogo-RJ,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,3,2,PR,RJ,NaN

In [394]:
# Verificando colunas do DataFrame
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado',
       'arrecadacao'],
      dtype='str')

In [395]:
# Mantendo apenas as colunas que serão utilizadas
df = df[['rodata','data','mandante','visitante','vencedor', 'mandante_Placar', 'visitante_Placar']]

In [396]:
# Contagem de linhas e colunas do DataFrame
df.shape

(9165, 7)

In [397]:
# Verificando tipos das colunas e valores nulos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rodata            9165 non-null   int64
 1   data              9165 non-null   str
 2   mandante          9165 non-null   str
 3   visitante         9165 non-null   str
 4   vencedor          9165 non-null   str
 5   mandante_Placar   9165 non-null   int64
 6   visitante_Placar  9165 non-null   int64
dtypes: int64(3), str(4)
memory usage: 501.3 KB

In [398]:
# Corrigindo coluna data para o tipo datetime
df['data'] = pd.to_datetime(df['data'], format='%d/%m/%Y')

In [399]:
# Renomeando colunas para facilitar a manipulação dos dados
df = df.rename(columns={'rodata':'rodada', 'data':'data', 'mandante':'mandante', 'visitante':'visitante', 'vencedor':'vencedor', 'mandante_Placar':'placar_mandante', 'visitante_Placar':'placar_visitante'})

In [400]:
# Filtrando apenas os jogos a partir de 2006, ano em que o campeonato brasileiro passou a ser disputado no formato atual
df = df[df['data'] >= '01/01/2006']

In [401]:
# Nova quantidade de linhas do DataFrame após o filtro
df.shape

(7599, 7)

In [402]:
df.head()

,rodada,data,mandante,visitante,vencedor,placar_mandante,placar_visitante
1566,1,2006-04-15,Juventude,Parana,Juventude,1,0
1567,1,2006-04-15,Vasco,Internacional,-,1,1
1568,1,2006-04-16,Sao Paulo,Flamengo,Sao Paulo,1,0
1569,1,2006-04-16,Gremio,Corinthians,Gremio,2,0
1570,1,2006-04-16,Botafogo-RJ,Fortaleza,Botafogo-RJ,1,0

In [403]:
# Arrumando o índice do DataFrame após o filtro
df = df.reset_index(drop=True)

In [404]:
# Verificando o período de tempo dos dados
print(df['data'].min())
print(df['data'].max())

2006-04-15 00:00:00
2025-12-07 00:00:00

In [405]:
# Criando a coluna 'ano'
df['ano'] = df['data'].dt.year

In [406]:
# Condições pontuação do time mandante
condicoes = [
    df['placar_mandante'] > df['placar_visitante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_visitante'] > df['placar_mandante']
]

# Quantidade de pontos baseado na condição
resultados = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_mandante'] = np.select(condicoes, resultados)

In [407]:
# Condições pontuação do time visitante
condicoes = [
    df['placar_visitante'] > df['placar_mandante'],
    df['placar_mandante'] == df['placar_visitante'],
    df['placar_mandante'] > df['placar_visitante']
]

# Quantidade de pontos baseado na condição
resultados = [3, 1, 0]

# Adição da coluna com as pontuações calculadas
df['pontos_visitante'] = np.select(condicoes, resultados)

In [408]:
df

,rodada,data,mandante,visitante,vencedor,placar_mandante,placar_visitante,ano,pontos_mandante,pontos_visitante
0,1,2006-04-15,Juventude,Parana,Juventude,1,0,2006,3,0
1,1,2006-04-15,Vasco,Internacional,-,1,1,2006,1,1
2,1,2006-04-16,Sao Paulo,Flamengo,Sao Paulo,1,0,2006,3,0
3,1,2006-04-16,Gremio,Corinthians,Gremio,2,0,2006,3,0
4,1,2006-04-16,Botafogo-RJ,Fortaleza,Botafogo-RJ,1,0,2006,3,0
...,...,...,...,...,...,...,...,...,...,...
7594,38,2025-12-07,Santos,Cruzeiro,Santos,3,0,2025,3,0
7595,38,2025-12-07,Sport,Gremio,Gremio,0,4,2025,0,3
7596,38,2025-12-07,Botafogo-RJ,Fortaleza,Botafogo-RJ,4,2,2025,3,0
7597,38,2025-12-07,Atletico-MG,Vasco,Atletico-MG,5,0,2025,3,0
7598,38,2025-12-07,Internacional,Bragantino,Internacional,3,1,2025,3,0

In [409]:
# Criando dataframe apenas com os jogos dos times mandante
df_mandante = df[['rodada', 'ano', 'mandante', 'placar_mandante', 'placar_visitante', 'pontos_mandante']]

# Renomeando as colunas
df_mandante = df_mandante.rename(columns={'rodada':'rodada', 'ano':'ano', 'mandante':'time', 'placar_mandante':'gols_pro', 'placar_visitante':'gols_contra', 'pontos_mandante':'pontos'})

df_mandante.head()

   rodada   ano         time  gols_pro  gols_contra  pontos
0       1  2006    Juventude         1            0       3
1       1  2006        Vasco         1            1       1
2       1  2006    Sao Paulo         1            0       3
3       1  2006       Gremio         2            0       3
4       1  2006  Botafogo-RJ         1            0       3

In [410]:
# Criando dataframe apenas com os jogos dos times visitantes
df_visitante = df[['rodada', 'ano', 'visitante', 'placar_visitante', 'placar_mandante', 'pontos_visitante']]

# Renomeando as colunas
df_visitante = df_visitante.rename(columns={'rodada':'rodada', 'ano':'ano', 'visitante':'time', 'placar_visitante':'gols_pro', 'placar_mandante':'gols_contra', 'pontos_visitante':'pontos'})

df_visitante.head()

   rodada   ano           time  gols_pro  gols_contra  pontos
0       1  2006         Parana         0            1       0
1       1  2006  Internacional         1            1       1
2       1  2006       Flamengo         0            1       0
3       1  2006    Corinthians         0            2       0
4       1  2006      Fortaleza         0            1       0

In [411]:
df_tabela_total = pd.concat([df_mandante, df_visitante])

In [412]:
df_2024 = df_tabela_total[df_tabela_total['ano'] == 2024]
df_2024.groupby(df_2024['time']).sum().sort_values(by=['pontos'], ascending=False)

               rodada    ano  gols_pro  gols_contra  pontos
time
Botafogo-RJ       741  76912        59           29      79
Palmeiras         741  76912        60           33      73
Flamengo          741  76912        61           42      70
Fortaleza         741  76912        53           39      68
Internacional     741  76912        53           36      65
Sao Paulo         741  76912        53           43      59
Corinthians       741  76912        54           45      56
Bahia             741  76912        49           49      53
Cruzeiro          741  76912        43           41      52
Vasco             741  76912        43           56      50
Atletico-MG       741  76912        47           54      47
Vitoria           741  76912        45           52      47
Fluminense        741  76912        33           39      46
Juventude         741  76912        48           59      45
Gremio            741  76912        44           50      45
Bragantino        741  76912        44           48      44
Athletico-PR      741  76912        40           46      42
Criciuma          741  76912        42           61      38
Atletico-GO       741  76912        29           58      30
Cuiaba            741  76912        29           49      30